### ISSUE TITLE
[error by upgrading acceptance-testing master_on_apache_with_sqlite

### ISSUE THREAD

**Issue by rperezb** [owncloud-archive/acceptance-testing#23]
By upgrading master_on_apache_with_sqlite
#### Logs

```
================================================================================

Error executing action `get` on resource 'http_request[enabling provisioning_api]'
================================================================================

Net::HTTPFatalError
-------------------
500 "Internal Server Error"

Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/owncloud/recipes/default.rb

361:   end
362:   http_request "enabling provisioning_api" do
363:     url "http://localhost/enable_provisioning_api.php"
364:     message :some => "value" # Hash.new
365:   end
366:   file "var/www/enable_provisioning_api.php" do

Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/owncloud/recipes/default.rb:362:in `from_file'

http_request("enabling provisioning_api") do
  retry_delay 2
  url "http://localhost/enable_provisioning_api.php"
  message {:some=>"value"}
  retries 0
  recipe_name "default"
  action :get
  cookbook_name :owncloud
end

[2013-03-21T07:45:48+00:00] ERROR: Running exception handlers
[2013-03-21T07:45:48+00:00] ERROR: Exception handlers complete
[2013-03-21T07:45:48+00:00] FATAL: Stacktrace dumped to /tmp/vagrant-chef-1/chef-stacktrace.out
[2013-03-21T07:45:48+00:00] FATAL: Net::HTTPFatalError: http_request[enabling provisioning_api] (owncloud::default line 362) had an error: Net::HTTPFatalError: 500 "Internal Server Error"
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by DeepDiver1975** [comment]
@jakobsack can you please have a look? THX

**Comment by jakobsack** [comment]
I will have a look after monday.

**Comment by jakobsack** [comment]
I think that this has something to do with the removal of the provisioning API, I have to replace the current implementation anyway.

**Comment by rperezb** [comment]
It is still not possible to upgrade acceptance-testing

### Logs

```
================================================================================

Error executing action `get` on resource 'http_request[enabling provisioning_api]'

================================================================================

Net::HTTPFatalError
-------------------
500 "Internal Server Error"

Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/owncloud/recipes/default.rb

361:   end
362:   http_request "enabling provisioning_api" do
363:     url "http://localhost/enable_provisioning_api.php"
364:     message :some => "value" # Hash.new
365:   end
366:   file "var/www/enable_provisioning_api.php" do

Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/owncloud/recipes/default.rb:362:in `from_file'

http_request("enabling provisioning_api") do
  retry_delay 2
  url "http://localhost/enable_provisioning_api.php"
  message {:some=>"value"}
  retries 0
  recipe_name "default"
  action :get
  cookbook_name :owncloud
end

[2013-04-01T06:42:02+00:00] ERROR: Running exception handlers
[2013-04-01T06:42:02+00:00] ERROR: Exception handlers complete
[2013-04-01T06:42:02+00:00] FATAL: Stacktrace dumped to /tmp/vagrant-chef-1/chef-stacktrace.out
[2013-04-01T06:42:02+00:00] FATAL: Net::HTTPFatalError: http_request[enabling provisioning_api] (owncloud::default line 362) had an error: Net::HTTPFatalError: 500 "Internal Server Error"
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by karlitschek** [comment]
@rperezb What exact versions have you tested here? The provisioning api is not released yet.

**Comment by jakobsack** [comment]
Sorry, didn't have enough time to work on ownCloud again. As I said the provisioning API has been removed and I have to hack around this issue.

**Comment by rperezb** [comment]
Just wanted to check the state of this issue

**Comment by Gomez** [comment]
fixed and removed provisioning API
