### ISSUE TITLE
Create vm with ruby, cucumber 

### ISSUE THREAD

**Issue by Gomez** [owncloud-archive/acceptance-testing#28]
I moved the ruby install into a branch. Its does not work and i have no idea why.

@jakobsack: If you find time, you can look here:

https://github.com/owncloud/acceptance-testing/tree/with_ruby_install

**Comment by jakobsack** [comment]
I think I know what's the error. I'll try to fix it tomorrow!

**Comment by Gomez** [comment]
Still getting this error:

[2013-08-22T10:43:10+00:00] INFO: rbenv_ruby[1.9.3-p194] is building, this may take a while...

# 

# Error executing action `install` on resource 'rbenv_gem[bundler]'

## Mixlib::ShellOut::ShellCommandFailed

Expected process to exit with [0], but received '1'
---- Begin output of /usr/bin/gem install bundler -q --no-rdoc --no-ri  -v "1.3.5"  ----
STDOUT: 
STDERR: ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /root/.gem/ruby/1.9.1/cache/bundler-1.3.5.gem
---- End output of /usr/bin/gem install bundler -q --no-rdoc --no-ri  -v "1.3.5"  ----
Ran /usr/bin/gem install bundler -q --no-rdoc --no-ri  -v "1.3.5"  returned 1

## Cookbook Trace:

/tmp/vagrant-chef-1/chef-solo-1/cookbooks/rbenv/libraries/provider_rbenv_rubygems.rb:69:in `install_via_gem_command'
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/rbenv/libraries/provider_rbenv_rubygems.rb:52:in`install_package'

## Resource Declaration:

# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/owncloud-testing/recipes/default.rb

 48: rbenv_gem "bundler" do
 49:   ruby_version { local_ruby_version }
 50: end
 51: 

## Compiled Resource:

# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/owncloud-testing/recipes/default.rb:48:in `from_file'

 48: rbenv_gem "bundler" do
 49:   ruby_version { local_ruby_version }
 50: end
 51: 

## Compiled Resource:

# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/owncloud-testing/recipes/default.rb:48:in `from_file'

rbenv_gem("bundler") do
  provider Chef::Provider::Package::RbenvRubygems
  action :install
  retries 0
  retry_delay 2
  cookbook_name :"owncloud-testing"
  recipe_name "default"
  package_name "bundler"
  version "1.3.5"
end

[2013-08-22T10:49:18+00:00] INFO: Running queued delayed notifications before re-raising exception
[2013-08-22T10:49:18+00:00] INFO: template[/etc/postfix/main.cf] sending restart action to service[postfix](delayed)
[2013-08-22T10:49:18+00:00] INFO: service[postfix] restarted
[2013-08-22T10:49:18+00:00] INFO: template[apache2.conf] sending restart action to service[apache2](delayed)
[2013-08-22T10:49:20+00:00] INFO: service[apache2] restarted
[2013-08-22T10:49:20+00:00] INFO: execute[a2dissite default] sending restart action to service[apache2](delayed)
[2013-08-22T10:49:23+00:00] INFO: service[apache2] restarted
[2013-08-22T10:49:23+00:00] ERROR: Running exception handlers
[2013-08-22T10:49:23+00:00] ERROR: Exception handlers complete
[2013-08-22T10:49:23+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2013-08-22T10:49:23+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: rbenv_gem[bundler](owncloud-testing::default line 48) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /usr/bin/gem install bundler -q --no-rdoc --no-ri  -v "1.3.5"  ----
STDOUT: 
STDERR: ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /root/.gem/ruby/1.9.1/cache/bundler-1.3.5.gem
---- End output of /usr/bin/gem install bundler -q --no-rdoc --no-ri  -v "1.3.5"  ----
Ran /usr/bin/gem install bundler -q --no-rdoc --no-ri  -v "1.3.5"  returned 1
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by jakobsack** [comment]
@Gomez Can this bug be closed now? Last time I tested it did build with ruby and cucumber!

**Comment by Gomez** [comment]
Yes, tested it too. Will close it!
