### ISSUE TITLE
incompatible encoding regexp match

### ISSUE THREAD

**Issue by PVince81** [owncloud-archive/acceptance-testing#34]
Running the tests against OC 6 stable6,
I get this:

```
Background:                            # features/share_files_with_user.feature:7
    Given I am logged in                 # features/step_definitions/basic_steps.rb:2
    And I am in the "files" app          # features/step_definitions/basic_steps.rb:18
    And I have uploaded the "demo" files # features/step_definitions/files_steps.rb:2
      incompatible encoding regexp match (ASCII-8BIT regexp with UTF-8 string) (Encoding::CompatibilityError)
      ./features/step_definitions/files_steps.rb:5:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/files_steps.rb:4:in `glob'
      ./features/step_definitions/files_steps.rb:4:in `/^I have uploaded the "([^"]*)" files?$/'
      features/share_files_with_user.feature:11:in `And I have uploaded the "demo" files'
```

Not sure if it is my environment or the tests that are broken.

ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-linux]
cucumber 1.3.10

**Comment by PVince81** [comment]
This is when running the following:

```
cucumber HEADLESS=true BROWSER=webkit HOST=localhost/vincent features
```

**Comment by karlitschek** [comment]
:+1:

**Comment by PVince81** [comment]
@karlitschek this is not a PR :smiley:

**Comment by karlitschek** [comment]
Lol. True. Confused this with your new acceptance test. :-)

**Comment by Gomez** [comment]
Works against the vagrant box, would you try:

vagrant up
cucumber HOST=192.168.10.10 BROWSER='webkit' features

**Comment by PVince81** [comment]
I haven't setup vagrant yet actually, just ran cucumber locally.
I'll have a try later.
